CREATE TABLE IF NOT EXISTS receiver (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matric VARCHAR(255),
    name VARCHAR(255),
    phone VARCHAR(255) UNIQUE,
    role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS parcel (
    tracking_number INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight INTEGER,
    receiver_id BIGINT,
    delivery_status VARCHAR(255),
    receive_date VARCHAR(255),
    payment_status VARCHAR(255),
    receiver_phone VARCHAR(255),
    sender_phone VARCHAR(255),
    FOREIGN KEY (sender_id) REFERENCES sender(id)
);

INSERT INTO receiver (name, matric, phone, role) VALUES
('Ahmad Bin Ali', 'M12345', '0111111111', 'ROLE_SENDER'),
('Siti Aisyah', 'M12346', '0122222222', 'ROLE_SENDER'),
('Muhammad Faiz', 'M12347', '0133333333', 'ROLE_SENDER');

INSERT INTO parcel (weight, receiver_id, delivery_status, receive_date, payment_status, receiver_name, receiver_phone, sender_phone) VALUES
(5, 1, 'Delivered', '2025-06-10', 'Paid', 'Ahmad Bin Ali', '0111111111', '0191111001'),
(10, 2, 'In Transit', '2025-06-11', 'Pending', 'Siti Aisyah', '0122222222', '0191111002'),
(15, 3, 'Pending', '2025-06-12', 'Unpaid', 'Muhammad Faiz', '0133333333', '0191111003');

INSERT INTO staff (username, password, role) VALUES
('staff', 'staff123', 'ROLE_STAFF');
